version: "3.6"

networks:
  app:
  services:

volumes:
  series_pgdata:
    external: true

services:
  nginx:
    image: nginx:1.19
    container_name: series_nginx
    volumes:
      - ../certificates/nginx.key:/etc/nginx/certificates/nginx.key
      - ../certificates/nginx.crt:/etc/nginx/certificates/nginx.crt
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
    networks:
      - app
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ../server
    image: series_backend
    container_name: series_backend
    volumes:
      - ../server:/app
    env_file:
      - backend.env
    networks:
      - app
      - services
  postgresql:
    image: postgres:13
    container_name: series_db
    env_file:
      - postgresql.env
    volumes:
      - series_pgdata:/var/lib/postgresql/data
    networks:
      - services
